// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20230617024448_AddMoreSeeds")]
    partial class AddMoreSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 4,
                            Breed = "Golden Retriever",
                            Name = "Laika",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 5,
                            Breed = "Chimpanzee",
                            Name = "Enos",
                            Species = "Ape"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 6,
                            Breed = "Finn-Dorset",
                            Name = "Dolly",
                            Species = "Sheep"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 6,
                            Breed = "Terrier",
                            Name = "Belka",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 7,
                            Breed = "Terrier",
                            Name = "Strelka",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 3,
                            Breed = "Chimpanzee",
                            Name = "Ham",
                            Species = "Ape"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 46,
                            Breed = "Gorilla",
                            Name = "Koko",
                            Species = "Ape"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 4,
                            Breed = "Teddy",
                            Name = "Elliot",
                            Species = "Guinea Pig"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 3,
                            Breed = "Nine-Banded",
                            Name = "Bandito",
                            Species = "Armadillo"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 5,
                            Breed = "Theoretical",
                            Name = "Schroedinger",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
